.class public Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;
.super Ljava/lang/Object;
.source ""

# interfaces
.implements Ljava/io/Serializable;


# static fields
.field public static final A3V:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public static final A3W:Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;


# instance fields
.field public final A00:F

.field public final A01:F

.field public final A02:F

.field public final A03:F

.field public final A04:F

.field public final A05:I

.field public final A06:I

.field public final A07:I

.field public final A08:I

.field public final A09:I

.field public final A0A:I

.field public final A0B:I

.field public final A0C:I

.field public final A0D:I

.field public final A0E:I

.field public final A0F:I

.field public final A0G:I

.field public final A0H:I

.field public final A0I:I

.field public final A0J:I

.field public final A0K:I

.field public final A0L:I

.field public final A0M:I

.field public final A0N:I

.field public final A0O:I

.field public final A0P:I

.field public final A0Q:I

.field public final A0R:I

.field public final A0S:I

.field public final A0T:I

.field public final A0U:I

.field public final A0V:I

.field public final A0W:I

.field public final A0X:I

.field public final A0Y:I

.field public final A0Z:I

.field public final A0a:I

.field public final A0b:I

.field public final A0c:I

.field public final A0d:I

.field public final A0e:I

.field public final A0f:I

.field public final A0g:I

.field public final A0h:I

.field public final A0i:I

.field public final A0j:I

.field public final A0k:I

.field public final A0l:I

.field public final A0m:J

.field public final A0n:J

.field public final A0o:LX/2tq;

.field public final A0p:LX/2tq;

.field public final A0q:LX/2tq;

.field public final A0r:LX/2tq;

.field public final A0s:LX/2tq;

.field public final A0t:LX/2tq;

.field public final A0u:LX/2tq;

.field public final A0v:LX/2tq;

.field public final A0w:LX/1Se;

.field public final A0x:LX/1Sd;

.field public final A0y:LX/2to;

.field public final A0z:LX/2tn;

.field public final A10:LX/2tp;

.field public final A11:LX/1Sc;

.field public final A12:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public final A13:LX/2tl;

.field public final A14:LX/2tr;

.field public final A15:LX/1UI;

.field public final A16:LX/1Sg;

.field public final A17:LX/2tk;

.field public final A18:LX/2tk;

.field public final A19:LX/1Sf;

.field public final A1A:Ljava/lang/String;

.field public final A1B:Ljava/lang/String;

.field public final A1C:Ljava/lang/String;

.field public final A1D:Ljava/util/HashMap;

.field public final A1E:Ljava/util/Map;

.field public final A1F:Ljava/util/Set;

.field public final A1G:Ljava/util/Set;

.field public final A1H:Ljava/util/Set;

.field public final A1I:Ljava/util/Set;

.field public final A1J:Ljava/util/Set;

.field public final A1K:Z

.field public final A1L:Z

.field public final A1M:Z

.field public final A1N:Z

.field public final A1O:Z

.field public final A1P:Z

.field public final A1Q:Z

.field public final A1R:Z

.field public final A1S:Z

.field public final A1T:Z

.field public final A1U:Z

.field public final A1V:Z

.field public final A1W:Z

.field public final A1X:Z

.field public final A1Y:Z

.field public final A1Z:Z

.field public final A1a:Z

.field public final A1b:Z

.field public final A1c:Z

.field public final A1d:Z

.field public final A1e:Z

.field public final A1f:Z

.field public final A1g:Z

.field public final A1h:Z

.field public final A1i:Z

.field public final A1j:Z

.field public final A1k:Z

.field public final A1l:Z

.field public final A1m:Z

.field public final A1n:Z

.field public final A1o:Z

.field public final A1p:Z

.field public final A1q:Z

.field public final A1r:Z

.field public final A1s:Z

.field public final A1t:Z

.field public final A1u:Z

.field public final A1v:Z

.field public final A1w:Z

.field public final A1x:Z

.field public final A1y:Z

.field public final A1z:Z

.field public final A20:Z

.field public final A21:Z

.field public final A22:Z

.field public final A23:Z

.field public final A24:Z

.field public final A25:Z

.field public final A26:Z

.field public final A27:Z

.field public final A28:Z

.field public final A29:Z

.field public final A2A:Z

.field public final A2B:Z

.field public final A2C:Z

.field public final A2D:Z

.field public final A2E:Z

.field public final A2F:Z

.field public final A2G:Z

.field public final A2H:Z

.field public final A2I:Z

.field public final A2J:Z

.field public final A2K:Z

.field public final A2L:Z

.field public final A2M:Z

.field public final A2N:Z

.field public final A2O:Z

.field public final A2P:Z

.field public final A2Q:Z

.field public final A2R:Z

.field public final A2S:Z

.field public final A2T:Z

.field public final A2U:Z

.field public final A2V:Z

.field public final A2W:Z

.field public final A2X:Z

.field public final A2Y:Z

.field public final A2Z:Z

.field public final A2a:Z

.field public final A2b:Z

.field public final A2c:Z

.field public final A2d:Z

.field public final A2e:Z

.field public final A2f:Z

.field public final A2g:Z

.field public final A2h:Z

.field public final A2i:Z

.field public final A2j:Z

.field public final A2k:Z

.field public final A2l:Z

.field public final A2m:Z

.field public final A2n:Z

.field public final A2o:Z

.field public final A2p:Z

.field public final A2q:Z

.field public final A2r:Z

.field public final A2s:Z

.field public final A2t:Z

.field public final A2u:Z

.field public final A2v:Z

.field public final A2w:Z

.field public final A2x:Z

.field public final A2y:Z

.field public final A2z:Z

.field public final A30:Z

.field public final A31:Z

.field public final A32:Z

.field public final A33:Z

.field public final A34:Z

.field public final A35:Z

.field public final A36:Z

.field public final A37:Z

.field public final A38:Z

.field public final A39:Z

.field public final A3A:Z

.field public final A3B:Z

.field public final A3C:Z

.field public final A3D:Z

.field public final A3E:Z

.field public final A3F:Z

.field public final A3G:Z

.field public final A3H:Z

.field public final A3I:Z

.field public final A3J:Z

.field public final A3K:Z

.field public final A3L:Z

.field public final A3M:Z

.field public final A3N:Z

.field public final A3O:Z

.field public final A3P:Z

.field public final A3Q:Z

.field public final A3R:Z

.field public final A3S:Z

.field public final A3T:Z

.field public final A3U:Z


# direct methods
.method public static constructor <clinit>()V
    .locals 2

    .line 0
    new-instance v1, LX/3Dt;

    .line 1
    .line 2
    invoke-direct {v1}, LX/3Dt;-><init>()V

    .line 3
    .line 4
    .line 5
    new-instance v0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;

    .line 6
    .line 7
    invoke-direct {v0, v1}, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;-><init>(LX/3Dt;)V

    .line 8
    .line 9
    .line 10
    sput-object v0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3W:Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;

    .line 11
    .line 12
    new-instance v0, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 13
    .line 14
    invoke-direct {v0}, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;-><init>()V

    .line 15
    .line 16
    .line 17
    sput-object v0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3V:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 18
    .line 19
    return-void
.end method

.method public constructor <init>(LX/3Dt;)V
    .locals 2

    .line 0
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 1
    .line 2
    .line 3
    iget-object v0, p1, LX/3Dt;->A12:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 4
    .line 5
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A12:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 6
    .line 7
    iget-boolean v0, p1, LX/3Dt;->A2b:Z

    .line 8
    .line 9
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2Z:Z

    .line 10
    .line 11
    iget-boolean v0, p1, LX/3Dt;->A34:Z

    .line 12
    .line 13
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A35:Z

    .line 14
    .line 15
    iget-boolean v0, p1, LX/3Dt;->A2F:Z

    .line 16
    .line 17
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2E:Z

    .line 18
    .line 19
    iget-boolean v0, p1, LX/3Dt;->A24:Z

    .line 20
    .line 21
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A23:Z

    .line 22
    .line 23
    iget-object v0, p1, LX/3Dt;->A1A:Ljava/lang/String;

    .line 24
    .line 25
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1A:Ljava/lang/String;

    .line 26
    .line 27
    iget-boolean v0, p1, LX/3Dt;->A22:Z

    .line 28
    .line 29
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A20:Z

    .line 30
    .line 31
    iget-boolean v0, p1, LX/3Dt;->A1m:Z

    .line 32
    .line 33
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1k:Z

    .line 34
    .line 35
    iget-boolean v0, p1, LX/3Dt;->A3K:Z

    .line 36
    .line 37
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3N:Z

    .line 38
    .line 39
    iget-boolean v0, p1, LX/3Dt;->A3O:Z

    .line 40
    .line 41
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3S:Z

    .line 42
    .line 43
    iget-object v0, p1, LX/3Dt;->A1C:Ljava/lang/String;

    .line 44
    .line 45
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1C:Ljava/lang/String;

    .line 46
    .line 47
    iget-boolean v0, p1, LX/3Dt;->A2c:Z

    .line 48
    .line 49
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2a:Z

    .line 50
    .line 51
    iget-object v0, p1, LX/3Dt;->A11:LX/1Sc;

    .line 52
    .line 53
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A11:LX/1Sc;

    .line 54
    .line 55
    iget-boolean v0, p1, LX/3Dt;->A2v:Z

    .line 56
    .line 57
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2w:Z

    .line 58
    .line 59
    iget-boolean v0, p1, LX/3Dt;->A2G:Z

    .line 60
    .line 61
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2F:Z

    .line 62
    .line 63
    iget-object v0, p1, LX/3Dt;->A17:LX/2tk;

    .line 64
    .line 65
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A17:LX/2tk;

    .line 66
    .line 67
    iget-object v0, p1, LX/3Dt;->A18:LX/2tk;

    .line 68
    .line 69
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A18:LX/2tk;

    .line 70
    .line 71
    iget-boolean v0, p1, LX/3Dt;->A1X:Z

    .line 72
    .line 73
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1U:Z

    .line 74
    .line 75
    iget-object v0, p1, LX/3Dt;->A13:LX/2tl;

    .line 76
    .line 77
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A13:LX/2tl;

    .line 78
    .line 79
    iget-boolean v0, p1, LX/3Dt;->A2q:Z

    .line 80
    .line 81
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2r:Z

    .line 82
    .line 83
    iget-boolean v0, p1, LX/3Dt;->A2u:Z

    .line 84
    .line 85
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2v:Z

    .line 86
    .line 87
    iget-boolean v0, p1, LX/3Dt;->A1N:Z

    .line 88
    .line 89
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1K:Z

    .line 90
    .line 91
    iget-boolean v0, p1, LX/3Dt;->A2t:Z

    .line 92
    .line 93
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2u:Z

    .line 94
    .line 95
    iget-object v0, p1, LX/3Dt;->A0z:LX/2tn;

    .line 96
    .line 97
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0z:LX/2tn;

    .line 98
    .line 99
    iget-object v0, p1, LX/3Dt;->A0y:LX/2to;

    .line 100
    .line 101
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0y:LX/2to;

    .line 102
    .line 103
    iget-object v0, p1, LX/3Dt;->A0x:LX/1Sd;

    .line 104
    .line 105
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0x:LX/1Sd;

    .line 106
    .line 107
    iget-object v0, p1, LX/3Dt;->A0w:LX/1Se;

    .line 108
    .line 109
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0w:LX/1Se;

    .line 110
    .line 111
    iget-object v0, p1, LX/3Dt;->A15:LX/1UI;

    .line 112
    .line 113
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A15:LX/1UI;

    .line 114
    .line 115
    iget-object v0, p1, LX/3Dt;->A10:LX/2tp;

    .line 116
    .line 117
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A10:LX/2tp;

    .line 118
    .line 119
    iget-boolean v0, p1, LX/3Dt;->A23:Z

    .line 120
    .line 121
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A21:Z

    .line 122
    .line 123
    iget-object v0, p1, LX/3Dt;->A19:LX/1Sf;

    .line 124
    .line 125
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A19:LX/1Sf;

    .line 126
    .line 127
    iget v0, p1, LX/3Dt;->A0C:I

    .line 128
    .line 129
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0C:I

    .line 130
    .line 131
    iget v0, p1, LX/3Dt;->A0B:I

    .line 132
    .line 133
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0B:I

    .line 134
    .line 135
    iget-object v0, p1, LX/3Dt;->A0p:LX/2tq;

    .line 136
    .line 137
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0p:LX/2tq;

    .line 138
    .line 139
    iget-object v0, p1, LX/3Dt;->A0q:LX/2tq;

    .line 140
    .line 141
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0q:LX/2tq;

    .line 142
    .line 143
    iget-object v0, p1, LX/3Dt;->A0s:LX/2tq;

    .line 144
    .line 145
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0s:LX/2tq;

    .line 146
    .line 147
    iget-object v0, p1, LX/3Dt;->A0t:LX/2tq;

    .line 148
    .line 149
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0t:LX/2tq;

    .line 150
    .line 151
    iget-boolean v0, p1, LX/3Dt;->A20:Z

    .line 152
    .line 153
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1y:Z

    .line 154
    .line 155
    iget-object v0, p1, LX/3Dt;->A0r:LX/2tq;

    .line 156
    .line 157
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0r:LX/2tq;

    .line 158
    .line 159
    iget-object v0, p1, LX/3Dt;->A0u:LX/2tq;

    .line 160
    .line 161
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0u:LX/2tq;

    .line 162
    .line 163
    iget-boolean v0, p1, LX/3Dt;->A2Q:Z

    .line 164
    .line 165
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2P:Z

    .line 166
    .line 167
    iget-boolean v0, p1, LX/3Dt;->A1Q:Z

    .line 168
    .line 169
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1N:Z

    .line 170
    .line 171
    iget-boolean v0, p1, LX/3Dt;->A39:Z

    .line 172
    .line 173
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3A:Z

    .line 174
    .line 175
    iget-boolean v0, p1, LX/3Dt;->A2X:Z

    .line 176
    .line 177
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2V:Z

    .line 178
    .line 179
    iget-wide v0, p1, LX/3Dt;->A0n:J

    .line 180
    .line 181
    iput-wide v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0n:J

    .line 182
    .line 183
    iget-boolean v0, p1, LX/3Dt;->A33:Z

    .line 184
    .line 185
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A34:Z

    .line 186
    .line 187
    iget-boolean v0, p1, LX/3Dt;->A1t:Z

    .line 188
    .line 189
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1r:Z

    .line 190
    .line 191
    iget-boolean v0, p1, LX/3Dt;->A2y:Z

    .line 192
    .line 193
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2z:Z

    .line 194
    .line 195
    iget-boolean v0, p1, LX/3Dt;->A1b:Z

    .line 196
    .line 197
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1Y:Z

    .line 198
    .line 199
    iget-boolean v0, p1, LX/3Dt;->A1k:Z

    .line 200
    .line 201
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1i:Z

    .line 202
    .line 203
    iget-boolean v0, p1, LX/3Dt;->A2i:Z

    .line 204
    .line 205
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2h:Z

    .line 206
    .line 207
    iget-boolean v0, p1, LX/3Dt;->A2n:Z

    .line 208
    .line 209
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2o:Z

    .line 210
    .line 211
    iget-boolean v0, p1, LX/3Dt;->A2W:Z

    .line 212
    .line 213
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2U:Z

    .line 214
    .line 215
    iget-boolean v0, p1, LX/3Dt;->A1O:Z

    .line 216
    .line 217
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1L:Z

    .line 218
    .line 219
    iget-boolean v0, p1, LX/3Dt;->A29:Z

    .line 220
    .line 221
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A28:Z

    .line 222
    .line 223
    iget-boolean v0, p1, LX/3Dt;->A28:Z

    .line 224
    .line 225
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A27:Z

    .line 226
    .line 227
    iget-boolean v0, p1, LX/3Dt;->A2A:Z

    .line 228
    .line 229
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A29:Z

    .line 230
    .line 231
    iget-boolean v0, p1, LX/3Dt;->A2B:Z

    .line 232
    .line 233
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2A:Z

    .line 234
    .line 235
    iget-boolean v0, p1, LX/3Dt;->A3H:Z

    .line 236
    .line 237
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3K:Z

    .line 238
    .line 239
    iget-object v0, p1, LX/3Dt;->A1B:Ljava/lang/String;

    .line 240
    .line 241
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1B:Ljava/lang/String;

    .line 242
    .line 243
    iget-boolean v0, p1, LX/3Dt;->A3U:Z

    .line 244
    .line 245
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3P:Z

    .line 246
    .line 247
    iget-boolean v0, p1, LX/3Dt;->A3S:Z

    .line 248
    .line 249
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3E:Z

    .line 250
    .line 251
    iget v0, p1, LX/3Dt;->A0O:I

    .line 252
    .line 253
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0O:I

    .line 254
    .line 255
    iget v0, p1, LX/3Dt;->A0P:I

    .line 256
    .line 257
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0P:I

    .line 258
    .line 259
    iget-boolean v0, p1, LX/3Dt;->A2d:Z

    .line 260
    .line 261
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2b:Z

    .line 262
    .line 263
    iget-boolean v0, p1, LX/3Dt;->A1c:Z

    .line 264
    .line 265
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1Z:Z

    .line 266
    .line 267
    iget-boolean v0, p1, LX/3Dt;->A3I:Z

    .line 268
    .line 269
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3L:Z

    .line 270
    .line 271
    iget-boolean v0, p1, LX/3Dt;->A2f:Z

    .line 272
    .line 273
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2f:Z

    .line 274
    .line 275
    iget-boolean v0, p1, LX/3Dt;->A2w:Z

    .line 276
    .line 277
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2x:Z

    .line 278
    .line 279
    iget-boolean v0, p1, LX/3Dt;->A2V:Z

    .line 280
    .line 281
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2e:Z

    .line 282
    .line 283
    iget-boolean v0, p1, LX/3Dt;->A2U:Z

    .line 284
    .line 285
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2c:Z

    .line 286
    .line 287
    iget-boolean v0, p1, LX/3Dt;->A3Q:Z

    .line 288
    .line 289
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3U:Z

    .line 290
    .line 291
    iget-boolean v0, p1, LX/3Dt;->A3P:Z

    .line 292
    .line 293
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3T:Z

    .line 294
    .line 295
    iget-boolean v0, p1, LX/3Dt;->A2j:Z

    .line 296
    .line 297
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2k:Z

    .line 298
    .line 299
    iget-boolean v0, p1, LX/3Dt;->A3A:Z

    .line 300
    .line 301
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3B:Z

    .line 302
    .line 303
    iget-boolean v0, p1, LX/3Dt;->A2g:Z

    .line 304
    .line 305
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2g:Z

    .line 306
    .line 307
    iget-boolean v0, p1, LX/3Dt;->A2h:Z

    .line 308
    .line 309
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2j:Z

    .line 310
    .line 311
    iget-boolean v0, p1, LX/3Dt;->A31:Z

    .line 312
    .line 313
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A32:Z

    .line 314
    .line 315
    iget-boolean v0, p1, LX/3Dt;->A2M:Z

    .line 316
    .line 317
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2L:Z

    .line 318
    .line 319
    iget-boolean v0, p1, LX/3Dt;->A2I:Z

    .line 320
    .line 321
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2H:Z

    .line 322
    .line 323
    iget-boolean v0, p1, LX/3Dt;->A2s:Z

    .line 324
    .line 325
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2t:Z

    .line 326
    .line 327
    iget-boolean v0, p1, LX/3Dt;->A3M:Z

    .line 328
    .line 329
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3Q:Z

    .line 330
    .line 331
    iget-boolean v0, p1, LX/3Dt;->A3G:Z

    .line 332
    .line 333
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3J:Z

    .line 334
    .line 335
    iget-boolean v0, p1, LX/3Dt;->A3D:Z

    .line 336
    .line 337
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3F:Z

    .line 338
    .line 339
    iget v0, p1, LX/3Dt;->A0J:I

    .line 340
    .line 341
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0J:I

    .line 342
    .line 343
    iget-boolean v0, p1, LX/3Dt;->A38:Z

    .line 344
    .line 345
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A39:Z

    .line 346
    .line 347
    iget-boolean v0, p1, LX/3Dt;->A2e:Z

    .line 348
    .line 349
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2d:Z

    .line 350
    .line 351
    iget-boolean v0, p1, LX/3Dt;->A37:Z

    .line 352
    .line 353
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A38:Z

    .line 354
    .line 355
    iget-boolean v0, p1, LX/3Dt;->A3L:Z

    .line 356
    .line 357
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3O:Z

    .line 358
    .line 359
    iget-boolean v0, p1, LX/3Dt;->A1Y:Z

    .line 360
    .line 361
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1V:Z

    .line 362
    .line 363
    iget v0, p1, LX/3Dt;->A0a:I

    .line 364
    .line 365
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0a:I

    .line 366
    .line 367
    iget-boolean v0, p1, LX/3Dt;->A2R:Z

    .line 368
    .line 369
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2Q:Z

    .line 370
    .line 371
    iget-boolean v0, p1, LX/3Dt;->A1d:Z

    .line 372
    .line 373
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1a:Z

    .line 374
    .line 375
    iget v0, p1, LX/3Dt;->A0X:I

    .line 376
    .line 377
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0X:I

    .line 378
    .line 379
    iget v0, p1, LX/3Dt;->A0W:I

    .line 380
    .line 381
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0W:I

    .line 382
    .line 383
    iget v0, p1, LX/3Dt;->A0K:I

    .line 384
    .line 385
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0K:I

    .line 386
    .line 387
    iget v0, p1, LX/3Dt;->A0L:I

    .line 388
    .line 389
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0L:I

    .line 390
    .line 391
    iget-boolean v0, p1, LX/3Dt;->A2m:Z

    .line 392
    .line 393
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2n:Z

    .line 394
    .line 395
    iget-boolean v0, p1, LX/3Dt;->A2x:Z

    .line 396
    .line 397
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2y:Z

    .line 398
    .line 399
    iget-boolean v0, p1, LX/3Dt;->A3R:Z

    .line 400
    .line 401
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2T:Z

    .line 402
    .line 403
    iget-boolean v0, p1, LX/3Dt;->A2L:Z

    .line 404
    .line 405
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2K:Z

    .line 406
    .line 407
    iget-boolean v0, p1, LX/3Dt;->A2S:Z

    .line 408
    .line 409
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2R:Z

    .line 410
    .line 411
    iget v0, p1, LX/3Dt;->A0N:I

    .line 412
    .line 413
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0N:I

    .line 414
    .line 415
    iget v0, p1, LX/3Dt;->A0M:I

    .line 416
    .line 417
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0M:I

    .line 418
    .line 419
    iget-boolean v0, p1, LX/3Dt;->A2N:Z

    .line 420
    .line 421
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2M:Z

    .line 422
    .line 423
    iget-boolean v0, p1, LX/3Dt;->A21:Z

    .line 424
    .line 425
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1z:Z

    .line 426
    .line 427
    iget-boolean v0, p1, LX/3Dt;->A2O:Z

    .line 428
    .line 429
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2N:Z

    .line 430
    .line 431
    iget v0, p1, LX/3Dt;->A0j:I

    .line 432
    .line 433
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0j:I

    .line 434
    .line 435
    iget-boolean v0, p1, LX/3Dt;->A2o:Z

    .line 436
    .line 437
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2p:Z

    .line 438
    .line 439
    iget-object v0, p1, LX/3Dt;->A1D:Ljava/util/HashMap;

    .line 440
    .line 441
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1D:Ljava/util/HashMap;

    .line 442
    .line 443
    iget v0, p1, LX/3Dt;->A0E:I

    .line 444
    .line 445
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0E:I

    .line 446
    .line 447
    iget v0, p1, LX/3Dt;->A0D:I

    .line 448
    .line 449
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0D:I

    .line 450
    .line 451
    iget-boolean v0, p1, LX/3Dt;->A1T:Z

    .line 452
    .line 453
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1Q:Z

    .line 454
    .line 455
    iget-boolean v0, p1, LX/3Dt;->A1V:Z

    .line 456
    .line 457
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1S:Z

    .line 458
    .line 459
    iget-boolean v0, p1, LX/3Dt;->A3T:Z

    .line 460
    .line 461
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3G:Z

    .line 462
    .line 463
    iget-boolean v0, p1, LX/3Dt;->A2K:Z

    .line 464
    .line 465
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2J:Z

    .line 466
    .line 467
    iget v0, p1, LX/3Dt;->A0b:I

    .line 468
    .line 469
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0b:I

    .line 470
    .line 471
    iget v0, p1, LX/3Dt;->A0c:I

    .line 472
    .line 473
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0c:I

    .line 474
    .line 475
    iget-boolean v0, p1, LX/3Dt;->A25:Z

    .line 476
    .line 477
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A24:Z

    .line 478
    .line 479
    iget-boolean v0, p1, LX/3Dt;->A1i:Z

    .line 480
    .line 481
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1g:Z

    .line 482
    .line 483
    iget-boolean v0, p1, LX/3Dt;->A2k:Z

    .line 484
    .line 485
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2l:Z

    .line 486
    .line 487
    iget-boolean v0, p1, LX/3Dt;->A1h:Z

    .line 488
    .line 489
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1f:Z

    .line 490
    .line 491
    iget-boolean v0, p1, LX/3Dt;->A1l:Z

    .line 492
    .line 493
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1j:Z

    .line 494
    .line 495
    iget-boolean v0, p1, LX/3Dt;->A2l:Z

    .line 496
    .line 497
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2m:Z

    .line 498
    .line 499
    iget-boolean v0, p1, LX/3Dt;->A30:Z

    .line 500
    .line 501
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A31:Z

    .line 502
    .line 503
    iget-boolean v0, p1, LX/3Dt;->A1P:Z

    .line 504
    .line 505
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1M:Z

    .line 506
    .line 507
    iget v0, p1, LX/3Dt;->A0Z:I

    .line 508
    .line 509
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0Z:I

    .line 510
    .line 511
    iget-boolean v0, p1, LX/3Dt;->A1e:Z

    .line 512
    .line 513
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1b:Z

    .line 514
    .line 515
    iget v0, p1, LX/3Dt;->A0U:I

    .line 516
    .line 517
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0U:I

    .line 518
    .line 519
    iget v0, p1, LX/3Dt;->A04:F

    .line 520
    .line 521
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A04:F

    .line 522
    .line 523
    iget v0, p1, LX/3Dt;->A03:F

    .line 524
    .line 525
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A03:F

    .line 526
    .line 527
    iget-boolean v0, p1, LX/3Dt;->A1g:Z

    .line 528
    .line 529
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1d:Z

    .line 530
    .line 531
    iget v0, p1, LX/3Dt;->A0V:I

    .line 532
    .line 533
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0V:I

    .line 534
    .line 535
    iget v0, p1, LX/3Dt;->A01:F

    .line 536
    .line 537
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A01:F

    .line 538
    .line 539
    iget v0, p1, LX/3Dt;->A00:F

    .line 540
    .line 541
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A00:F

    .line 542
    .line 543
    iget v0, p1, LX/3Dt;->A02:F

    .line 544
    .line 545
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A02:F

    .line 546
    .line 547
    iget-boolean v0, p1, LX/3Dt;->A1f:Z

    .line 548
    .line 549
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1c:Z

    .line 550
    .line 551
    iget v0, p1, LX/3Dt;->A07:I

    .line 552
    .line 553
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A07:I

    .line 554
    .line 555
    iget v0, p1, LX/3Dt;->A09:I

    .line 556
    .line 557
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A09:I

    .line 558
    .line 559
    iget v0, p1, LX/3Dt;->A08:I

    .line 560
    .line 561
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A08:I

    .line 562
    .line 563
    iget-boolean v0, p1, LX/3Dt;->A1U:Z

    .line 564
    .line 565
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1R:Z

    .line 566
    .line 567
    iget-wide v0, p1, LX/3Dt;->A0m:J

    .line 568
    .line 569
    iput-wide v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0m:J

    .line 570
    .line 571
    iget-boolean v0, p1, LX/3Dt;->A1S:Z

    .line 572
    .line 573
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1P:Z

    .line 574
    .line 575
    iget-boolean v0, p1, LX/3Dt;->A2r:Z

    .line 576
    .line 577
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2s:Z

    .line 578
    .line 579
    iget-boolean v0, p1, LX/3Dt;->A3B:Z

    .line 580
    .line 581
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3C:Z

    .line 582
    .line 583
    iget v0, p1, LX/3Dt;->A0T:I

    .line 584
    .line 585
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0T:I

    .line 586
    .line 587
    iget v0, p1, LX/3Dt;->A0d:I

    .line 588
    .line 589
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0d:I

    .line 590
    .line 591
    iget v0, p1, LX/3Dt;->A0e:I

    .line 592
    .line 593
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0e:I

    .line 594
    .line 595
    iget v0, p1, LX/3Dt;->A0g:I

    .line 596
    .line 597
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0g:I

    .line 598
    .line 599
    iget v0, p1, LX/3Dt;->A0f:I

    .line 600
    .line 601
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0f:I

    .line 602
    .line 603
    iget v0, p1, LX/3Dt;->A0S:I

    .line 604
    .line 605
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0S:I

    .line 606
    .line 607
    iget-boolean v0, p1, LX/3Dt;->A27:Z

    .line 608
    .line 609
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A26:Z

    .line 610
    .line 611
    iget-boolean v0, p1, LX/3Dt;->A2D:Z

    .line 612
    .line 613
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2C:Z

    .line 614
    .line 615
    iget v0, p1, LX/3Dt;->A0Y:I

    .line 616
    .line 617
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0Y:I

    .line 618
    .line 619
    iget-boolean v0, p1, LX/3Dt;->A1q:Z

    .line 620
    .line 621
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1o:Z

    .line 622
    .line 623
    iget-boolean v0, p1, LX/3Dt;->A2J:Z

    .line 624
    .line 625
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2I:Z

    .line 626
    .line 627
    iget-boolean v0, p1, LX/3Dt;->A26:Z

    .line 628
    .line 629
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A25:Z

    .line 630
    .line 631
    iget v0, p1, LX/3Dt;->A0l:I

    .line 632
    .line 633
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0l:I

    .line 634
    .line 635
    iget v0, p1, LX/3Dt;->A0k:I

    .line 636
    .line 637
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0k:I

    .line 638
    .line 639
    iget-boolean v0, p1, LX/3Dt;->A3N:Z

    .line 640
    .line 641
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3R:Z

    .line 642
    .line 643
    iget-boolean v0, p1, LX/3Dt;->A3C:Z

    .line 644
    .line 645
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3D:Z

    .line 646
    .line 647
    iget-object v0, p1, LX/3Dt;->A0v:LX/2tq;

    .line 648
    .line 649
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0v:LX/2tq;

    .line 650
    .line 651
    iget-object v0, p1, LX/3Dt;->A0o:LX/2tq;

    .line 652
    .line 653
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0o:LX/2tq;

    .line 654
    .line 655
    iget v0, p1, LX/3Dt;->A0G:I

    .line 656
    .line 657
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0G:I

    .line 658
    .line 659
    iget v0, p1, LX/3Dt;->A0F:I

    .line 660
    .line 661
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0F:I

    .line 662
    .line 663
    iget-boolean v0, p1, LX/3Dt;->A32:Z

    .line 664
    .line 665
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A33:Z

    .line 666
    .line 667
    iget-object v0, p1, LX/3Dt;->A1I:Ljava/util/Set;

    .line 668
    .line 669
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1I:Ljava/util/Set;

    .line 670
    .line 671
    iget-object v0, p1, LX/3Dt;->A1H:Ljava/util/Set;

    .line 672
    .line 673
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1H:Ljava/util/Set;

    .line 674
    .line 675
    iget-object v0, p1, LX/3Dt;->A1J:Ljava/util/Set;

    .line 676
    .line 677
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1J:Ljava/util/Set;

    .line 678
    .line 679
    iget-boolean v0, p1, LX/3Dt;->A1n:Z

    .line 680
    .line 681
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1l:Z

    .line 682
    .line 683
    iget v0, p1, LX/3Dt;->A0I:I

    .line 684
    .line 685
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0I:I

    .line 686
    .line 687
    iget v0, p1, LX/3Dt;->A0i:I

    .line 688
    .line 689
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0i:I

    .line 690
    .line 691
    iget v0, p1, LX/3Dt;->A0H:I

    .line 692
    .line 693
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0H:I

    .line 694
    .line 695
    iget v0, p1, LX/3Dt;->A05:I

    .line 696
    .line 697
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A05:I

    .line 698
    .line 699
    iget-boolean v0, p1, LX/3Dt;->A1w:Z

    .line 700
    .line 701
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1u:Z

    .line 702
    .line 703
    iget v0, p1, LX/3Dt;->A0R:I

    .line 704
    .line 705
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0R:I

    .line 706
    .line 707
    iget-boolean v0, p1, LX/3Dt;->A1v:Z

    .line 708
    .line 709
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1t:Z

    .line 710
    .line 711
    iget v0, p1, LX/3Dt;->A0Q:I

    .line 712
    .line 713
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0Q:I

    .line 714
    .line 715
    iget-boolean v0, p1, LX/3Dt;->A1Z:Z

    .line 716
    .line 717
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1W:Z

    .line 718
    .line 719
    iget v0, p1, LX/3Dt;->A06:I

    .line 720
    .line 721
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A06:I

    .line 722
    .line 723
    iget-boolean v0, p1, LX/3Dt;->A1M:Z

    .line 724
    .line 725
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2i:Z

    .line 726
    .line 727
    iget-boolean v0, p1, LX/3Dt;->A1L:Z

    .line 728
    .line 729
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A22:Z

    .line 730
    .line 731
    iget-boolean v0, p1, LX/3Dt;->A1K:Z

    .line 732
    .line 733
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1e:Z

    .line 734
    .line 735
    iget-boolean v0, p1, LX/3Dt;->A36:Z

    .line 736
    .line 737
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A37:Z

    .line 738
    .line 739
    iget v0, p1, LX/3Dt;->A0h:I

    .line 740
    .line 741
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0h:I

    .line 742
    .line 743
    iget-boolean v0, p1, LX/3Dt;->A1W:Z

    .line 744
    .line 745
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1T:Z

    .line 746
    .line 747
    iget-boolean v0, p1, LX/3Dt;->A2Z:Z

    .line 748
    .line 749
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2X:Z

    .line 750
    .line 751
    iget-boolean v0, p1, LX/3Dt;->A35:Z

    .line 752
    .line 753
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A36:Z

    .line 754
    .line 755
    iget-boolean v0, p1, LX/3Dt;->A1o:Z

    .line 756
    .line 757
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1m:Z

    .line 758
    .line 759
    iget-boolean v0, p1, LX/3Dt;->A1x:Z

    .line 760
    .line 761
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1v:Z

    .line 762
    .line 763
    iget-boolean v0, p1, LX/3Dt;->A1z:Z

    .line 764
    .line 765
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1x:Z

    .line 766
    .line 767
    iget-object v0, p1, LX/3Dt;->A14:LX/2tr;

    .line 768
    .line 769
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A14:LX/2tr;

    .line 770
    .line 771
    iget-boolean v0, p1, LX/3Dt;->A2E:Z

    .line 772
    .line 773
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2D:Z

    .line 774
    .line 775
    iget-object v0, p1, LX/3Dt;->A1E:Ljava/util/Map;

    .line 776
    .line 777
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1E:Ljava/util/Map;

    .line 778
    .line 779
    iget-boolean v0, p1, LX/3Dt;->A1a:Z

    .line 780
    .line 781
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1X:Z

    .line 782
    .line 783
    iget-boolean v0, p1, LX/3Dt;->A2a:Z

    .line 784
    .line 785
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2Y:Z

    .line 786
    .line 787
    iget-boolean v0, p1, LX/3Dt;->A2T:Z

    .line 788
    .line 789
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2S:Z

    .line 790
    .line 791
    iget-boolean v0, p1, LX/3Dt;->A1R:Z

    .line 792
    .line 793
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1O:Z

    .line 794
    .line 795
    iget-boolean v0, p1, LX/3Dt;->A1p:Z

    .line 796
    .line 797
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1n:Z

    .line 798
    .line 799
    iget v0, p1, LX/3Dt;->A0A:I

    .line 800
    .line 801
    iput v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A0A:I

    .line 802
    .line 803
    iget-boolean v0, p1, LX/3Dt;->A1u:Z

    .line 804
    .line 805
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1s:Z

    .line 806
    .line 807
    iget-boolean v0, p1, LX/3Dt;->A3F:Z

    .line 808
    .line 809
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3I:Z

    .line 810
    .line 811
    iget-boolean v0, p1, LX/3Dt;->A3J:Z

    .line 812
    .line 813
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3M:Z

    .line 814
    .line 815
    iget-boolean v0, p1, LX/3Dt;->A2z:Z

    .line 816
    .line 817
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A30:Z

    .line 818
    .line 819
    iget-boolean v0, p1, LX/3Dt;->A1j:Z

    .line 820
    .line 821
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1h:Z

    .line 822
    .line 823
    iget-boolean v0, p1, LX/3Dt;->A2p:Z

    .line 824
    .line 825
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2q:Z

    .line 826
    .line 827
    iget-object v0, p1, LX/3Dt;->A1G:Ljava/util/Set;

    .line 828
    .line 829
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1G:Ljava/util/Set;

    .line 830
    .line 831
    iget-object v0, p1, LX/3Dt;->A1F:Ljava/util/Set;

    .line 832
    .line 833
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1F:Ljava/util/Set;

    .line 834
    .line 835
    iget-boolean v0, p1, LX/3Dt;->A2H:Z

    .line 836
    .line 837
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2G:Z

    .line 838
    .line 839
    iget-object v0, p1, LX/3Dt;->A16:LX/1Sg;

    .line 840
    .line 841
    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A16:LX/1Sg;

    .line 842
    .line 843
    iget-boolean v0, p1, LX/3Dt;->A2P:Z

    .line 844
    .line 845
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2O:Z

    .line 846
    .line 847
    iget-boolean v0, p1, LX/3Dt;->A2C:Z

    .line 848
    .line 849
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2B:Z

    .line 850
    .line 851
    iget-boolean v0, p1, LX/3Dt;->A1r:Z

    .line 852
    .line 853
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1p:Z

    .line 854
    .line 855
    iget-boolean v0, p1, LX/3Dt;->A1s:Z

    .line 856
    .line 857
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1q:Z

    .line 858
    .line 859
    iget-boolean v0, p1, LX/3Dt;->A3E:Z

    .line 860
    .line 861
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A3H:Z

    .line 862
    .line 863
    iget-boolean v0, p1, LX/3Dt;->A2Y:Z

    .line 864
    .line 865
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A2W:Z

    .line 866
    .line 867
    iget-boolean v0, p1, LX/3Dt;->A1y:Z

    .line 868
    .line 869
    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A1w:Z

    .line 870
    .line 871
    return-void
    .line 872
    .line 873
    .line 874
    .line 875
    .line 876
    .line 877
    .line 878
    .line 879
    .line 880
    .line 881
    .line 882
    .line 883
    .line 884
    .line 885
    .line 886
    .line 887
    .line 888
    .line 889
    .line 890
    .line 891
    .line 892
    .line 893
    .line 894
    .line 895
    .line 896
    .line 897
    .line 898
    .line 899
    .line 900
    .line 901
    .line 902
    .line 903
    .line 904
    .line 905
    .line 906
    .line 907
    .line 908
    .line 909
    .line 910
    .line 911
    .line 912
    .line 913
    .line 914
    .line 915
    .line 916
    .line 917
    .line 918
    .line 919
    .line 920
    .line 921
    .line 922
    .line 923
    .line 924
    .line 925
    .line 926
    .line 927
    .line 928
    .line 929
    .line 930
    .line 931
    .line 932
    .line 933
    .line 934
    .line 935
    .line 936
    .line 937
    .line 938
    .line 939
    .line 940
    .line 941
    .line 942
    .line 943
    .line 944
.end method
